// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketType int32

const (
	PacketType_INTERNAL     PacketType = 0
	PacketType_MESSAGE      PacketType = 1
	PacketType_BROADCAST    PacketType = 2
	PacketType_SEEK         PacketType = 3
	PacketType_REQUEST      PacketType = 4
	PacketType_RESPONSE     PacketType = 5
	PacketType_END_RESPONSE PacketType = 6
)

var PacketType_name = map[int32]string{
	0: "INTERNAL",
	1: "MESSAGE",
	2: "BROADCAST",
	3: "SEEK",
	4: "REQUEST",
	5: "RESPONSE",
	6: "END_RESPONSE",
}

var PacketType_value = map[string]int32{
	"INTERNAL":     0,
	"MESSAGE":      1,
	"BROADCAST":    2,
	"SEEK":         3,
	"REQUEST":      4,
	"RESPONSE":     5,
	"END_RESPONSE": 6,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type StreamPacket struct {
	Type                 PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=messages.PacketType" json:"type,omitempty"`
	Namespace            string     `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Content              []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lifespan             int64      `protobuf:"varint,5,opt,name=lifespan,proto3" json:"lifespan,omitempty"`
	ResponseTag          string     `protobuf:"bytes,6,opt,name=responseTag,proto3" json:"responseTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StreamPacket) Reset()         { *m = StreamPacket{} }
func (m *StreamPacket) String() string { return proto.CompactTextString(m) }
func (*StreamPacket) ProtoMessage()    {}
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *StreamPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamPacket.Unmarshal(m, b)
}
func (m *StreamPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamPacket.Marshal(b, m, deterministic)
}
func (m *StreamPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamPacket.Merge(m, src)
}
func (m *StreamPacket) XXX_Size() int {
	return xxx_messageInfo_StreamPacket.Size(m)
}
func (m *StreamPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamPacket.DiscardUnknown(m)
}

var xxx_messageInfo_StreamPacket proto.InternalMessageInfo

func (m *StreamPacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_INTERNAL
}

func (m *StreamPacket) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *StreamPacket) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StreamPacket) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StreamPacket) GetLifespan() int64 {
	if m != nil {
		return m.Lifespan
	}
	return 0
}

func (m *StreamPacket) GetResponseTag() string {
	if m != nil {
		return m.ResponseTag
	}
	return ""
}

type SecureStreamPacket struct {
	Packet               *StreamPacket `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	Signature            []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Source               []byte        `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SecureStreamPacket) Reset()         { *m = SecureStreamPacket{} }
func (m *SecureStreamPacket) String() string { return proto.CompactTextString(m) }
func (*SecureStreamPacket) ProtoMessage()    {}
func (*SecureStreamPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SecureStreamPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecureStreamPacket.Unmarshal(m, b)
}
func (m *SecureStreamPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecureStreamPacket.Marshal(b, m, deterministic)
}
func (m *SecureStreamPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecureStreamPacket.Merge(m, src)
}
func (m *SecureStreamPacket) XXX_Size() int {
	return xxx_messageInfo_SecureStreamPacket.Size(m)
}
func (m *SecureStreamPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SecureStreamPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SecureStreamPacket proto.InternalMessageInfo

func (m *SecureStreamPacket) GetPacket() *StreamPacket {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *SecureStreamPacket) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SecureStreamPacket) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func init() {
	proto.RegisterEnum("messages.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*StreamPacket)(nil), "messages.StreamPacket")
	proto.RegisterType((*SecureStreamPacket)(nil), "messages.SecureStreamPacket")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0xd7, 0x10, 0x42, 0x18, 0xb2, 0xc8, 0xb2, 0x56, 0xc8, 0x5a, 0xed, 0x21, 0xe2, 0x14,
	0xed, 0x81, 0x03, 0x7d, 0x82, 0xb4, 0x58, 0x55, 0xd5, 0x36, 0x50, 0x3b, 0x3d, 0x57, 0x6e, 0x34,
	0x45, 0xa8, 0x4d, 0x62, 0xc5, 0xe6, 0x40, 0x9f, 0xb1, 0x0f, 0x55, 0x25, 0xfc, 0x09, 0xbd, 0xf9,
	0xfb, 0xe6, 0x9b, 0xb1, 0x7f, 0x1e, 0x98, 0x14, 0x68, 0xad, 0xde, 0xa0, 0x9d, 0x9b, 0xba, 0x72,
	0x15, 0x0b, 0x4e, 0x7a, 0xf6, 0x45, 0x20, 0x54, 0xae, 0x46, 0x5d, 0xac, 0x75, 0xfe, 0x8e, 0x8e,
	0xc5, 0xe0, 0xb9, 0xbd, 0x41, 0x4e, 0x22, 0x12, 0x4f, 0x16, 0x7f, 0xe6, 0xe7, 0xce, 0x43, 0x3d,
	0xdb, 0x1b, 0x94, 0x6d, 0x82, 0xfd, 0x83, 0x51, 0xa9, 0x0b, 0xb4, 0x46, 0xe7, 0xc8, 0x7b, 0x11,
	0x89, 0x47, 0xb2, 0x33, 0x18, 0x87, 0x61, 0x5e, 0x95, 0x0e, 0x4b, 0xc7, 0xfb, 0x11, 0x89, 0x43,
	0x79, 0x92, 0x4d, 0x9f, 0xdb, 0x16, 0x68, 0x9d, 0x2e, 0x0c, 0xf7, 0x22, 0x12, 0xf7, 0x65, 0x67,
	0xb0, 0xbf, 0x10, 0x7c, 0x6c, 0xdf, 0x9a, 0x21, 0x25, 0x1f, 0xb4, 0xc5, 0xb3, 0x66, 0x11, 0x8c,
	0x6b, 0xb4, 0xa6, 0x2a, 0x2d, 0x66, 0x7a, 0xc3, 0xfd, 0xf6, 0xce, 0x4b, 0x6b, 0xf6, 0x09, 0x4c,
	0x61, 0xbe, 0xab, 0xf1, 0x07, 0xd3, 0x1c, 0x7c, 0xd3, 0x9e, 0x5a, 0xaa, 0xf1, 0x62, 0xda, 0x51,
	0x5d, 0xe6, 0xe4, 0x31, 0xd5, 0xbc, 0xd0, 0x6e, 0x37, 0xa5, 0x76, 0xbb, 0xfa, 0x40, 0x16, 0xca,
	0xce, 0x60, 0x53, 0xf0, 0x6d, 0xb5, 0xab, 0x73, 0x3c, 0x82, 0x1d, 0xd5, 0xff, 0x02, 0xa0, 0xfb,
	0x23, 0x16, 0x42, 0x70, 0x97, 0x66, 0x42, 0xa6, 0xc9, 0x03, 0xfd, 0xc5, 0xc6, 0x30, 0x7c, 0x14,
	0x4a, 0x25, 0xb7, 0x82, 0x12, 0xf6, 0x1b, 0x46, 0xd7, 0x72, 0x95, 0x2c, 0x6f, 0x12, 0x95, 0xd1,
	0x1e, 0x0b, 0xc0, 0x53, 0x42, 0xdc, 0xd3, 0x7e, 0x93, 0x92, 0xe2, 0xe9, 0x59, 0xa8, 0x8c, 0x7a,
	0xcd, 0x00, 0x29, 0xd4, 0x7a, 0x95, 0x2a, 0x41, 0x07, 0x8c, 0x42, 0x28, 0xd2, 0xe5, 0xcb, 0xd9,
	0xf1, 0x5f, 0xfd, 0x76, 0x95, 0x57, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x49, 0xc6, 0x45, 0x4d,
	0xdc, 0x01, 0x00, 0x00,
}
